spring.application.name=poc-020-azure-container-registry-mycomplex
server.port=${SERVER_PORT:8080}

app.version=${APP_VERSION:dev}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
