spring.application.name=poc-009-firebase-push-mycomplex
server.port=${SERVER_PORT:8082}

# Ruta local al JSON generado en Firebase Console > Project settings > Service accounts.
# NO subas ese archivo al repositorio.
firebase.credentials.path=${FIREBASE_CREDENTIALS:}
