spring.application.name=poc-015-application-insights-mycomplex
server.port=${SERVER_PORT:8086}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.mycomplex=INFO
