spring.application.name=poc-007-autorizacion-mycomplex

# Usa el mismo tenant Auth0 de la PoC-006.
auth0.issuer=${AUTH0_ISSUER:https://mycomplex-dev.us.auth0.com/}

# Debe coincidir con el Identifier de MyComplex API en Auth0.
auth0.audience=${AUTH0_AUDIENCE:https://api.mycomplex.com}

server.port=${SERVER_PORT:8081}
